In [384]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.linear_model import LogisticRegression

import sys
sys.path.insert(1, '/Users/bolin/Desktop/NUS_Y4S2/BT4222/BT4222_repo')
from custom_utils import *

In [385]:
df = pd.read_csv("/Users/bolin/Desktop/NUS_Y4S2/BT4222/BT4222_repo/data/cooked_data/cooked_complete_dataset.csv")
# prevent 0 division zero
df = df.replace(0, 1)

In [386]:
df

date  Adj_Close_BTC-USD  Open_BTC-USD  High_BTC-USD  Low_BTC-USD  \
0    2020-12-14        19246.64453   19144.49219   19305.09961  19012.70898   
1    2020-12-15        19417.07617   19246.91992   19525.00781  19079.84180   
2    2020-12-16        21310.59766   19418.81836   21458.90820  19298.31641   
3    2020-12-17        22805.16211   21308.35156   23642.66016  21234.67578   
4    2020-12-18        23137.96094   22806.79688   23238.60156  22399.81250   
..          ...                ...           ...           ...          ...   
109  2021-04-02        59384.31250   59098.87890   60267.18750  58869.28130   
110  2021-04-03        57603.89060   59397.41020   60110.26950  57603.89060   
111  2021-04-04        58758.55470   57604.83980   58913.74610  57168.67580   
112  2021-04-05        59057.87890   58760.87500   59891.29690  57694.82420   
113  2021-04-06        58192.35938   59171.93359   59479.57813  57646.80859   

     Volume_BTC-USD  Adj_Close_SPY  Adj_Close_GLD  Adj_Close_CHFUSD=X  \
0      2.247400e+10     361.926788     171.539993            1.125442   
1      2.674198e+10     366.819824     173.940002            1.127930   
2      4.440901e+10     367.395508     174.899994            1.129382   
3      7.137861e+10     369.449982     176.740005            1.129446   
4      4.038790e+10     367.974792     176.440002            1.130301   
..              ...            ...            ...                 ...   
109    5.870000e+10     400.609985     161.979996            1.061447   
110    5.960000e+10     400.609985     161.979996            1.061447   
111    5.080000e+10     400.609985     161.979996            1.061447   
112    6.070000e+10     406.359985     161.919998            1.061571   
113    6.605803e+10     406.119995     163.220001            1.068330   

     Adj_Close_CNYUSD=X  Adj_Close_EURUSD=X  Adj_Close_GBPUSD=X  \
0              0.152772            1.213340            1.331824   
1              0.152679            1.214890            1.333084   
2              0.152945            1.215430            1.344447   
3              0.153109            1.219959            1.350293   
4              0.153090            1.226272            1.357018   
..                  ...                 ...                 ...   
109            0.152337            1.177995            1.383509   
110            0.152337            1.177995            1.383509   
111            0.152337            1.177995            1.383509   
112            0.152288            1.176817            1.383126   
113            0.152302            1.181893            1.391401   

     Adj_Close_JPYUSD=X  coindesk_sentiment  num_of_coindesk_posts  \
0              0.009621            0.249489                     12   
1              0.009614            0.173773                     18   
2              0.009649            0.341491                     11   
3              0.009664            0.197572                     10   
4              0.009696            0.315601                      2   
..                  ...                 ...                    ...   
109            0.009041            0.121955                     10   
110            0.009041            0.501192                      1   
111            0.009041            0.206128                      1   
112            0.009035            0.179058                     21   
113            0.009075            0.214637                     24   

     reddit_comments_sentiments  top_50_reddit_posts_sentiments  \
0                      0.188275                        0.297238   
1                      0.144389                        0.399427   
2                      0.137256                        0.489673   
3                      0.156723                        0.636030   
4                      0.166419                        0.107093   
..                          ...                             ...   
109                    0.146423                        0.152625   
110

In [387]:
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')

In [388]:
df.columns

Index(['date', 'Adj_Close_BTC-USD', 'Open_BTC-USD', 'High_BTC-USD',
       'Low_BTC-USD', 'Volume_BTC-USD', 'Adj_Close_SPY', 'Adj_Close_GLD',
       'Adj_Close_CHFUSD=X', 'Adj_Close_CNYUSD=X', 'Adj_Close_EURUSD=X',
       'Adj_Close_GBPUSD=X', 'Adj_Close_JPYUSD=X', 'coindesk_sentiment',
       'num_of_coindesk_posts', 'reddit_comments_sentiments',
       'top_50_reddit_posts_sentiments', 'blockchain_transactions_per_block',
       'blockchain_hash_rates'],
      dtype='object')

In [389]:
# conduct log return transformation on all columns
df = log_return_transformation(df)

In [390]:
# custom number of lags for selected columns
# columns that are not specify in this dictionary will be lagged by on by default
lags = {
    'Adj_Close_BTC-USD': 6,
    'Open_BTC-USD': 6,
    'Low_BTC-USD': 6,
    'Volume_BTC-USD': 6,
    'Adj_Close_SPY': 6,
    'Adj_Close_GLD': 6,
}

In [391]:
df = get_num_lags(df, lags)

/Users/bolin/Desktop/NUS_Y4S2/BT4222/BT4222_repo/custom_utils/get_num_lags.py:23: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column + '_lag_' + str(i)] = df[column].shift(i)


In [392]:
df.columns

Index(['date', 'Adj_Close_BTC-USD', 'Open_BTC-USD_lag_1', 'Open_BTC-USD_lag_2',
       'Open_BTC-USD_lag_3', 'Open_BTC-USD_lag_4', 'Open_BTC-USD_lag_5',
       'High_BTC-USD_lag_1', 'Low_BTC-USD_lag_1', 'Low_BTC-USD_lag_2',
       'Low_BTC-USD_lag_3', 'Low_BTC-USD_lag_4', 'Low_BTC-USD_lag_5',
       'Volume_BTC-USD_lag_1', 'Volume_BTC-USD_lag_2', 'Volume_BTC-USD_lag_3',
       'Volume_BTC-USD_lag_4', 'Volume_BTC-USD_lag_5', 'Adj_Close_SPY_lag_1',
       'Adj_Close_SPY_lag_2', 'Adj_Close_SPY_lag_3', 'Adj_Close_SPY_lag_4',
       'Adj_Close_SPY_lag_5', 'Adj_Close_GLD_lag_1', 'Adj_Close_GLD_lag_2',
       'Adj_Close_GLD_lag_3', 'Adj_Close_GLD_lag_4', 'Adj_Close_GLD_lag_5',
       'Adj_Close_CHFUSD=X_lag_1', 'Adj_Close_CNYUSD=X_lag_1',
       'Adj_Close_EURUSD=X_lag_1', 'Adj_Close_GBPUSD=X_lag_1',
       'Adj_Close_JPYUSD=X_lag_1', 'coindesk_sentiment_lag_1',
       'num_of_coindesk_posts_lag_1', 'reddit_comments_sentiments_lag_1',
       'top_50_reddit_posts_sentiments_lag_1',
       'blo

In [393]:
df['Adj_Close_BTC-USD'] = df['Adj_Close_BTC-USD'].apply(lambda x: 1 if x > 0 else 0)

In [394]:
train = df[df['date']<'2021-03-11'].sort_values('date')
test = df[df['date']>='2021-03-11'].sort_values('date')

In [395]:
train

date  Adj_Close_BTC-USD  Open_BTC-USD_lag_1  Open_BTC-USD_lag_2  \
6  2020-12-20                  0            0.014196            0.067960   
7  2020-12-21                  0            0.031023            0.014196   
8  2020-12-22                  1           -0.016365            0.031023   
9  2020-12-23                  0           -0.029414           -0.016365   
10 2020-12-24                  1            0.042429           -0.029414   
..        ...                ...                 ...                 ...   
82 2021-03-06                  0           -0.040294            0.042588   
83 2021-03-07                  1            0.007641           -0.040294   
84 2021-03-08                  1            0.000398            0.007641   
85 2021-03-09                  1            0.045075            0.000398   
86 2021-03-10                  1            0.021246            0.045075   

    Open_BTC-USD_lag_3  Open_BTC-USD_lag_4  Open_BTC-USD_lag_5  \
6             0.092856            0.008892            0.005336   
7             0.067960            0.092856            0.008892   
8             0.014196            0.067960            0.092856   
9             0.031023            0.014196            0.067960   
10           -0.016365            0.031023            0.014196   
..                 ...                 ...                 ...   
82           -0.024408            0.094034           -0.022650   
83            0.042588           -0.024408            0.094034   
84           -0.040294            0.042588           -0.024408   
85            0.007641           -0.040294            0.042588   
86            0.000398            0.007641           -0.040294   

    High_BTC-USD_lag_1  Low_BTC-USD_lag_1  Low_BTC-USD_lag_2  ...  \
6             0.035810           0.018868           0.053417  ...   
7             0.005127           0.013975           0.018868  ...   
8            -0.006202          -0.043636           0.013975  ...   
9            -0.011289           0.012166          -0.043636  ...   
10            0.009813           0.016450           0.012166  ...   
..                 ...                ...                ...  ...   
82           -0.046258          -0.023662          -0.012872  ...   
83           -0.005058           0.015246          -0.023662  ...   
84            0.044514           0.034547           0.015246  ...   
85            0.017931           0.011936           0.034547  ...   
86            0.046865           0.048799           0.011936  ...   

    Adj_Close_CNYUSD=X_lag_1  Adj_Close_EURUSD=X_lag_1  \
6                   0.000000                  0.000000   
7                   0.000000                  0.000000   
8                  -0.000597                  0.000000   
9                  -0.001865                 -0.002107   
10                  0.000917                 -0.004115   
..                       ...                       ...   
82                 -0.000340                 -0.006905   
83                  0.000000                  0.000000   
84                  0.000000                  0.000000   
85                 -0.004119                 -0.003524   
86                 -0.004439                 -0.006218   

    Adj_Close_GBPUSD=X_lag_1  Adj_Close_JPYUSD=X_lag_1  \
6                   0.000000                  0.000000   
7                   0.000000                  0.000000   
8                  -0.012474                 -0.003156   
9                   0.003544                  0.001132   
10                 -0.003732                 -0.001875   
..                       ...                       ...   
82                 -0.002365                 -0.008344   
83                  0.000000                  0.000000   
84                  0.000000                  0.000000   
85                 -0.002913                 -0.004289   
86                 -0.002173                 -0.004785   

    coindesk_sentiment_lag_1  num_of_coindesk_posts_lag_1  \
6                  

In [396]:
test

date  Adj_Close_BTC-USD  Open_BTC-USD_lag_1  Open_BTC-USD_lag_2  \
87  2021-03-11                  1            0.047649            0.021246   
88  2021-03-12                  0            0.020566            0.047649   
89  2021-03-13                  1            0.032662            0.020566   
90  2021-03-14                  0           -0.008299            0.032662   
91  2021-03-15                  0            0.065435           -0.008299   
92  2021-03-16                  1           -0.032433            0.065435   
93  2021-03-17                  1           -0.059555           -0.032433   
94  2021-03-18                  0            0.017486           -0.059555   
95  2021-03-19                  1            0.035733            0.017486   
96  2021-03-20                  0           -0.017862            0.035733   
97  2021-03-21                  0            0.008294           -0.017862   
98  2021-03-22                  0           -0.000383            0.008294   
99  2021-03-23                  1           -0.013676           -0.000383   
100 2021-03-24                  0           -0.053681           -0.013676   
101 2021-03-25                  0            0.003641           -0.053681   
102 2021-03-26                  1           -0.036933            0.003641   
103 2021-03-27                  1           -0.019994           -0.036933   
104 2021-03-28                  0            0.064702           -0.019994   
105 2021-03-29                  1            0.015073            0.064702   
106 2021-03-30                  1           -0.000483            0.015073   
107 2021-03-31                  1            0.031705           -0.000483   
108 2021-04-01                  1            0.020229            0.031705   
109 2021-04-02                  1           -0.000063            0.020229   
110 2021-04-03                  0            0.002920           -0.000063   
111 2021-04-04                  1            0.005039            0.002920   
112 2021-04-05                  1           -0.030644            0.005039   

     Open_BTC-USD_lag_3  Open_BTC-USD_lag_4  Open_BTC-USD_lag_5  \
87             0.045075            0.000398            0.007641   
88             0.021246            0.045075            0.000398   
89             0.047649            0.021246            0.045075   
90             0.020566            0.047649            0.021246   
91             0.032662            0.020566            0.047649   
92            -0.008299            0.032662            0.020566   
93             0.065435           -0.008299            0.032662   
94            -0.032433            0.065435           -0.008299   
95            -0.059555           -0.032433            0.065435   
96             0.017486           -0.059555           -0.032433   
97             0.035733            0.017486           -0.059555   
98            -0.017862            0.035733            0.017486   
99             0.008294           -0.017862            0.035733   
100           -0.000383            0.008294           -0.017862   
101           -0.013676           -0.000383            0.008294   
102           -0.053681           -0.013676           -0.000383   
103            0.003641           -0.053681           -0.013676   
104           -0.036933            0.003641           -0.053681   
105           -0.019994           -0.036933            0.003641   
106            0.064702           -0.019994           -0.036933   
107            0.015073            0.064702           -0.019994   
108           -0.000483            0.015073            0.064702   
109            0.031705           -0.000483            0.015073   
110            0.020229            0.031705           -0.000483   
111           -0.000063            0.020229            0.031705   
112            0.002920           -0.000063            0.020229   

     High_BTC-USD_lag_1  Low_BTC-USD_lag_1  Low_BTC-USD_lag_2  ...  \
87             0.043442           0.024871        

In [397]:
y_train = train['Adj_Close_BTC-USD']
X_train = train.iloc[:,2:]
X_train_no_sentiment = X_train.drop(['coindesk_sentiment_lag_1', 'num_of_coindesk_posts_lag_1', 'reddit_comments_sentiments_lag_1', 'top_50_reddit_posts_sentiments_lag_1'], axis=1)


y_test = test['Adj_Close_BTC-USD']
X_test = test.iloc[:,2:]
X_test_no_sentiment = X_test.drop(['coindesk_sentiment_lag_1', 'num_of_coindesk_posts_lag_1', 'reddit_comments_sentiments_lag_1', 'top_50_reddit_posts_sentiments_lag_1'], axis=1)


In [398]:
y_train.value_counts()

1    46
0    35
Name: Adj_Close_BTC-USD, dtype: int64

In [399]:
y_test.value_counts()

1    15
0    11
Name: Adj_Close_BTC-USD, dtype: int64

### Logistic regression with complete set of independent variables (With sentiments)

In [400]:
lr = LogisticRegression(max_iter=500, solver='liblinear')
lr.fit(X_train, y_train)

LogisticRegression(max_iter=500, solver='liblinear')

In [401]:
y_pred_class = lr.predict(X_train)
print('Accuracy score in training set: {}'.format(metrics.accuracy_score(y_train, y_pred_class)))
print('Precision score in training set: {}'.format(metrics.precision_score(y_train, y_pred_class)))
print('Recall score in training set: {}'.format(metrics.recall_score(y_train, y_pred_class)))
print('Confusion matrix:')
print(metrics.confusion_matrix(y_train, y_pred_class))

y_pred_prob = lr.predict_proba(X_train)[:, 1]
print('ROC_AUC score in training set: {}'.format(metrics.roc_auc_score(y_train, y_pred_prob)))

print('*'*80)

y_pred_class = lr.predict(X_test)
print('Accuracy score in test set: {}'.format(metrics.accuracy_score(y_test, y_pred_class)))
print('Precision score in test set: {}'.format(metrics.precision_score(y_test, y_pred_class)))
print('Recall score in test set: {}'.format(metrics.recall_score(y_test, y_pred_class)))
print('Confusion matrix:')
print(metrics.confusion_matrix(y_test, y_pred_class))

y_pred_prob = lr.predict_proba(X_test)[:, 1]
print('ROC_AUC score in test set: {}'.format(metrics.roc_auc_score(y_test, y_pred_prob)))

Accuracy score in training set: 0.654320987654321
Precision score in training set: 0.65
Recall score in training set: 0.8478260869565217
Confusion matrix:
[[14 21]
 [ 7 39]]
ROC_AUC score in training set: 0.6819875776397516
********************************************************************************
Accuracy score in test set: 0.5384615384615384
Precision score in test set: 0.5789473684210527
Recall score in test set: 0.7333333333333333
Confusion matrix:
[[ 3  8]
 [ 4 11]]
ROC_AUC score in test set: 0.48484848484848486


### Logistic regression with complete set of independent variables (Without sentiments)

In [402]:
lr = LogisticRegression(max_iter=500, solver='liblinear')
lr.fit(X_train_no_sentiment, y_train)

LogisticRegression(max_iter=500, solver='liblinear')

In [403]:
y_pred_class = lr.predict(X_train_no_sentiment)
print('Accuracy score in training set: {}'.format(metrics.accuracy_score(y_train, y_pred_class)))
print('Precision score in training set: {}'.format(metrics.precision_score(y_train, y_pred_class)))
print('Recall score in training set: {}'.format(metrics.recall_score(y_train, y_pred_class)))
print('Confusion matrix:')
print(metrics.confusion_matrix(y_train, y_pred_class))

y_pred_prob = lr.predict_proba(X_train_no_sentiment)[:, 1]
print('ROC_AUC score in training set: {}'.format(metrics.roc_auc_score(y_train, y_pred_prob)))

print('*'*80)

y_pred_class = lr.predict(X_test_no_sentiment)
print('Accuracy score in test set: {}'.format(metrics.accuracy_score(y_test, y_pred_class)))
print('Precision score in test set: {}'.format(metrics.precision_score(y_test, y_pred_class)))
print('Recall score in test set: {}'.format(metrics.recall_score(y_test, y_pred_class)))
print('Confusion matrix:')
print(metrics.confusion_matrix(y_test, y_pred_class))

y_pred_prob = lr.predict_proba(X_test_no_sentiment)[:, 1]
print('ROC_AUC score in test set: {}'.format(metrics.roc_auc_score(y_test, y_pred_prob)))

Accuracy score in training set: 0.6172839506172839
Precision score in training set: 0.6119402985074627
Recall score in training set: 0.8913043478260869
Confusion matrix:
[[ 9 26]
 [ 5 41]]
ROC_AUC score in training set: 0.6447204968944099
********************************************************************************
Accuracy score in test set: 0.46153846153846156
Precision score in test set: 0.5217391304347826
Recall score in test set: 0.8
Confusion matrix:
[[ 0 11]
 [ 3 12]]
ROC_AUC score in test set: 0.32727272727272727


### Logistic regression with selected set of independent variables from stepwise regression (With Sentiment)

In [404]:
selected_x_variables = "coindesk_sentiment_lag_1 + Adj_Close_GLD_lag_2 + top_50_reddit_posts_sentiments_lag_1 + Volume_BTC-USD_lag_3 + blockchain_transactions_per_block_lag_1"
selected_x_variables = selected_x_variables.split(' + ')

In [405]:
selected_x_variables

['coindesk_sentiment_lag_1',
 'Adj_Close_GLD_lag_2',
 'top_50_reddit_posts_sentiments_lag_1',
 'Volume_BTC-USD_lag_3',
 'blockchain_transactions_per_block_lag_1']

In [406]:
new_X_train = X_train[selected_x_variables]
new_X_test = X_test[selected_x_variables]

In [407]:
lr = LogisticRegression(max_iter=500, solver='liblinear')
lr.fit(new_X_train, y_train)

LogisticRegression(max_iter=500, solver='liblinear')

In [408]:
output_with_sentiment = []
y_pred_class = lr.predict(new_X_train)
output_with_sentiment = output_with_sentiment + list(y_pred_class)

print('Accuracy score in training set: {}'.format(metrics.accuracy_score(y_train, y_pred_class)))
print('Precision score in training set: {}'.format(metrics.precision_score(y_train, y_pred_class)))
print('Recall score in training set: {}'.format(metrics.recall_score(y_train, y_pred_class)))
print('Confusion matrix:')
print(metrics.confusion_matrix(y_train, y_pred_class))

y_pred_prob = lr.predict_proba(new_X_train)[:, 1]
print('ROC_AUC score in training set: {}'.format(metrics.roc_auc_score(y_train, y_pred_prob)))

print('*'*80)

y_pred_class = lr.predict(new_X_test)
output_with_sentiment = output_with_sentiment + list(y_pred_class)

print('Accuracy score in test set: {}'.format(metrics.accuracy_score(y_test, y_pred_class)))
print('Precision score in test set: {}'.format(metrics.precision_score(y_test, y_pred_class)))
print('Recall score in test set: {}'.format(metrics.recall_score(y_test, y_pred_class)))
print('Confusion matrix:')
print(metrics.confusion_matrix(y_test, y_pred_class))

y_pred_prob = lr.predict_proba(new_X_test)[:, 1]
print('ROC_AUC score in test set: {}'.format(metrics.roc_auc_score(y_test, y_pred_prob)))

Accuracy score in training set: 0.5679012345679012
Precision score in training set: 0.5873015873015873
Recall score in training set: 0.8043478260869565
Confusion matrix:
[[ 9 26]
 [ 9 37]]
ROC_AUC score in training set: 0.6322981366459628
********************************************************************************
Accuracy score in test set: 0.6153846153846154
Precision score in test set: 0.631578947368421
Recall score in test set: 0.8
Confusion matrix:
[[ 4  7]
 [ 3 12]]
ROC_AUC score in test set: 0.6363636363636364


### Logistic regression with selected set of independent variables from stepwise regression (Without Sentiment) 

In [409]:
selected_x_variables = "Adj_Close_GLD_lag_1 + Adj_Close_GLD_lag_2 + Volume_BTC-USD_lag_5 + Volume_BTC-USD_lag_3"
selected_x_variables = selected_x_variables.split(' + ')

In [410]:
selected_x_variables

['Adj_Close_GLD_lag_1',
 'Adj_Close_GLD_lag_2',
 'Volume_BTC-USD_lag_5',
 'Volume_BTC-USD_lag_3']

In [411]:
new_X_train = X_train[selected_x_variables]
new_X_test = X_test[selected_x_variables]

In [412]:
lr = LogisticRegression(max_iter=500, solver='liblinear')
lr.fit(new_X_train, y_train)

LogisticRegression(max_iter=500, solver='liblinear')

In [413]:
output_without_sentiment = []
y_pred_class = lr.predict(new_X_train)
output_without_sentiment = output_without_sentiment + list(y_pred_class)
print('Accuracy score in training set: {}'.format(metrics.accuracy_score(y_train, y_pred_class)))
print('Precision score in training set: {}'.format(metrics.precision_score(y_train, y_pred_class)))
print('Recall score in training set: {}'.format(metrics.recall_score(y_train, y_pred_class)))
print('Confusion matrix:')
print(metrics.confusion_matrix(y_train, y_pred_class))

y_pred_prob = lr.predict_proba(new_X_train)[:, 1]
print('ROC_AUC score in training set: {}'.format(metrics.roc_auc_score(y_train, y_pred_prob)))

print('*'*80)

y_pred_class = lr.predict(new_X_test)
output_without_sentiment = output_without_sentiment + list(y_pred_class)
print('Accuracy score in test set: {}'.format(metrics.accuracy_score(y_test, y_pred_class)))
print('Precision score in test set: {}'.format(metrics.precision_score(y_test, y_pred_class)))
print('Recall score in test set: {}'.format(metrics.recall_score(y_test, y_pred_class)))
print('Confusion matrix:')
print(metrics.confusion_matrix(y_test, y_pred_class))

y_pred_prob = lr.predict_proba(new_X_test)[:, 1]
print('ROC_AUC score in test set: {}'.format(metrics.roc_auc_score(y_test, y_pred_prob)))

Accuracy score in training set: 0.5925925925925926
Precision score in training set: 0.5915492957746479
Recall score in training set: 0.9130434782608695
Confusion matrix:
[[ 6 29]
 [ 4 42]]
ROC_AUC score in training set: 0.6186335403726708
********************************************************************************
Accuracy score in test set: 0.5
Precision score in test set: 0.5416666666666666
Recall score in test set: 0.8666666666666667
Confusion matrix:
[[ 0 11]
 [ 2 13]]
ROC_AUC score in test set: 0.2909090909090909


In [414]:
predictions = {
    'prediction_with_sentiments': output_with_sentiment,
    'predictions_without_sentiments': output_without_sentiment,
    'date': list(train['date']) + list(test['date'])
}

In [415]:
pd.DataFrame(predictions).to_csv('logistic_predictions.csv', index=False)